# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 406a6b5f84a9cc690e79f10a4adb8288dad7fb0c230ffdbf274f0f93f45df40a3db57184f3153778f1bd19a1dcb973d69072152edf85ee46253eea6dd03b476b

test:
  secret_key_base: 9927d4133fdf2d76e795896a46a38763496c63d892f1faf289717259bad04f872424fbe3b69511d78e4ef449f8d531223c9f672e3a60f2c4743ff64d1a4eca2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
